name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew
        
    - name: Build with Gradle Wrapper
      run: ./gradlew :plugin-core:shadowJar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: plugin-jar
        path: plugin-core/build/libs/*.jar

    - name: Get latest commit messages
      id: commit_messages
      run: |
        TAG=$(git tag | sort -V | tail -n 1 || echo "v0.0.0")  # Pobierz ostatni tag lub ustaw "v0.0.0" jako domyślny
        COMMITS=$(git log --pretty=format:'- %s' $TAG..HEAD | tr '\n' ';')  # Wiadomości commitów od ostatniego tagu do HEAD
        echo "COMMITS=$COMMITS" >> $GITHUB_ENV
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Check build/libs contents
      run: |
        if [ -d "build/libs" ]; then
          ls build/libs/
        else
          echo "Brak katalogu build/libs. Kompilacja mogła nie zakończyć się powodzeniem."
        fi

    - name: Calculate new version tag
      id: new_tag
      run: |
        TAG=$(echo ${{ env.TAG }} | sed 's/^v//')  # Usuń prefix 'v'
        VERSION=$((TAG + 1))  # Zwiększ numer wersji o 1
        NEW_TAG="v$VERSION"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo "Nowy tag to $NEW_TAG"

    - name: Create Git tag for release
      run: |
        git tag "${{ env.NEW_TAG }}"
        git push origin "${{ env.NEW_TAG }}"

    - name: Create Release with commit messages
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.NEW_TAG }}
        body: |
          ## Zmiany w tej wersji:
          ${{ env.COMMITS }}
        files: build/libs/Navigation-${{ env.NEW_TAG }}.jar  # Nazwa pliku JAR z nowym tagiem
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
